services:
  veji-me:
    container_name: veji-me-api
    build:
      context: .
      dockerfile: dockerfile.api
    ports:
      - "3333:3333"
    networks:
      - "veji-me-network"

  postgres:
    image: bitnami/postgresql:latest
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=short_links
    networks:
      - "veji-me-network"

networks: 
  veji-me-network:
      driver: bridge